### PR TITLE
#27, #28, #35 issues fix + Black statusbar patch

### PR DESCRIPTION
**Pull request by hexlay**
Fix for:
- Google Photos image retrieving
- Bottomsheet flickering in multi select mode
- Crash when directory does not exist
- Black statusbar

### CODE REVIEW

**Comment by ParkSangGwon** [comment]
@prophet173 Thanks about your `pull request`. Please resolve conflict

**Comment by prophet173** [comment]
fixing this conflict means to remove Google Photo solution, as i see... which is main reason i created pull request, i don`t understand the conflict caused here

**Comment by DaniyarAmangeldy** [comment]
@prophet173 Thank you for pull req. Any progress?

**Comment by ParkSangGwon** [comment]
@prophet173 Becoz I updated some code for issue.
your pull request code is old version code.
So branch has conflicts.
You can update recent code and merge some code.
And then pull request again please

**Pull request closed without merging**
